import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Google clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <header>
          {/* left */}
        <div className="flex space-x-4 items-center text-red-800">
          <p className="text-red-800">About</p>
          <p>Store</p>
          <p>Store</p>
        </div>
          {/* right */}
        <div className="flex space-x-4 items-center">
          <p>Gmail</p>
          <p>Images</p>
        </div>
      </header>

      {/* Body */}

      {/* Footer */}


    </div>
  )
}
