import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Google clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <header>
        <div>
          {/* left */}
          <p>About</p>
          <p>Store</p>
        </div>
        <div>
          {/* right */}
          <p>Gmail</p>
          <p>Images</p>
        </div>
      </header>

      {/* Body */}

      {/* Footer */}


      <h1 className="p-10">let creat something</h1>
    </div>
  )
}
