import Head from 'next/head'
import Avatar from '../components/Avatar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Google clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <header className="flex w-full p-5 justify-between text-gray-700 text-sm">
          {/* left */}
        <div className="flex space-x-4 items-center">
          <p className="link">About</p>
          <p className="link">Store</p>
        </div>
          {/* right */}
        <div className="flex space-x-4 items-center">
          <p className="link">Gmail</p>
          <p className="link">Images</p>
        </div>
      </header>

      {/* icon */}

      {/* Avatar */}
      <Avatar url="" />
      {/* Body */}

      {/* Footer */}


    </div>
  )
}
